name: qr_bar_code_scanner_dialog_example
description: Demonstrates how to use the qr_bar_code_scanner_dialog plugin.
publish_to: none
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  qr_bar_code_scanner_dialog:
    path: ../
  cupertino_icons: ^1.0.2
  flutter_smart_dialog: ^4.9.6+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
