name: qr_bar_code_scanner_dialog
description: Plugin to show a simple scanner dialog and capture Bar/QR code easily. Works with Android iOS and Web. It uses html5-qrcode scanner for web and qr_code_scanner for Android and iOS
version: 0.0.5
homepage: 'https://github.com/Afinas-nl/qr-bar-code-scanner-dialog'
environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=2.5.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.2
  flutter_scankit: ^2.0.3
  flutter_smart_dialog: ^4.9.6+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.northladder.qr_bar_code_scanner_dialog
        pluginClass: QrBarCodeScannerDialogPlugin
      ios:
        pluginClass: QrBarCodeScannerDialogPlugin
      web:
        pluginClass: QrBarCodeScannerDialogWeb
        fileName: qr_bar_code_scanner_dialog_web.dart
